In [2]:
import requests, os, pandas as pd

In [3]:
# need to setup the code inside data_ingestion.py
from dotenv import load_dotenv
load_dotenv() #this gets the API key from .env file so we can use it.
API_KEY = os.getenv("API_KEY")

<p>Here, we're making an events API call to TicketMaster and querying music events in New York City <br>
for the time period of May 1, 2025 to Dec 31, 2027 just to make sure that we are able to pull up sufficient data.<br> 
Then checking for successful status code for the API call that confirms our setup is correct. <br>
We then retrieve the response data back as a JSON so that we can work with this data format.</p>

In [4]:
events_url = f'https://app.ticketmaster.com/discovery/v2/events.json?apikey={API_KEY}'

In [5]:

events_params_action_api = {
    'startDateTime': '2025-05-01T18:00:00-05:00',
    'endDateTime': '2027-12-31T17:00:00-05:00',
    'classificationName': 'music',
    'dmaId': '345', 
    'city': 'New York',
    'size': '20', 
    'page': '5'
}

In [6]:
r = requests.get(events_url, params=events_params_action_api)
print(r.status_code)
data=r.json()

200

In [7]:
# with open('output.txt', 'wt') as f:
#     print(data, file=f)

In [8]:
print(data.keys())

dict_keys(['_embedded', '_links', 'page'])

In [9]:
print(data['page'])

{'size': 20, 'totalElements': 722, 'totalPages': 37, 'number': 5}

In [10]:
print(len(data['_embedded']['events']))

20

In [11]:
print(data)

{'_embedded': {'events': [{'name': 'Alabama Shakes', 'type': 'event', 'id': 'G5dYZ_F-Hysua', 'test': False, 'url': 'https://www.ticketmaster.com/alabama-shakes-new-york-new-york-09-02-2026/event/3C0064887CE71349', 'locale': 'en-us', 'images': [{'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_SOURCE', 'width': 2426, 'height': 1728, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_LANDSCAPE_16_9.jpg', 'width': 1136, 'height': 639, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_PORTRAIT_16_9.jpg', 'width': 640, 'height': 360, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_LARGE_16_9.jpg', 'width': 2048, 'height': 1152, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_PORTRAIT_3_2.jpg', 'width': 640, 'height': 427, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_3_2.jpg', 'width': 1024, 'height': 683, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_16_9.jpg', 'width': 1024, 'height': 576, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_ARTIST_PAGE_3_2.jpg', 'width': 305, 'height': 203, 'fallback': False}, {'ratio': '4_3', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_CUSTOM.jpg', 'width': 305, 'height': 225, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_EVENT_DETAIL_PAGE_16_9.jpg', 'width': 205, 'height': 115, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RECOMENDATION_16_9.jpg', 'width': 100, 'height': 56, 'fallback': False}], 'sales': {'public': {'startDateTime': '2026-04-17T14:00:00Z', 'startTBD': False, 'startTBA': False, 'endDateTime': '2026-09-03T01:00:00Z'}, 'presales': [{'startDateTime': '2026-04-13T14:00:00Z', 'endDateTime': '2026-04-17T03:59:00Z', 'name': 'Citi® Cardmember Presale'}, {'startDateTime': '2026-04-14T14:00:00Z', 'endDateTime': '2026-04-17T03:59:00Z', 'name': 'Artist Presale'}, {'startDateTime': '2026-04-15T14:00:00Z', 'endDateTime': '2026-04-17T03:59:00Z', 'name': 'The Bowery Presents Presale'}, {'startDateTime': '2026-04-15T14:00:00Z', 'endDateTime': '2026-04-17T03:59:00Z', 'name': 'Venue Presale'}, {'startDateTime': '2026-04-17T14:00:00Z', 'endDateTime': '2026-09-03T01:00:00Z', 'name': 'Amex Reserved Tickets®'}, {'startDateTime': '2026-04-17T14:00:00Z', 'endDateTime': '2026-09-03T01:00:00Z', 'name': 'Chase Cardholder Preferred Tickets'}, {'startDateTime': '2026-04-17T14:00:00Z', 'endDateTime': '2026-09-03T01:00:00Z', 'name': 'Citi® Cardmember Preferred Tickets'}, {'startDateTime': '2026-04-17T14:00:00Z', 'endDateTime': '2026-05-18T14:00:00Z', 'name': 'Verizon Access Featured Venues'}, {'startDateTime': '2026-04-13T14:00:00Z', 'endDateTime': '2026-04-17T03:59:00Z', 'name': 'VIP Packages Presale'}, {'startDateTime': '2026-04-17T14:00:00Z', 'endDateTime': '2026-08-27T02:00:00Z', 'name': 'VIP Packages'}]}, 'dates': {'start': {'localDate': '2026-09-02', 'localTime': '20:00:00', 'dateTime': '2026-09-03T00:00:00Z', 'dateTBD': False, 'dateTBA': False, 'timeTBA': False, 'noSpecificTime': False}, 'timezone': 'America/New_York', 'status': {'code': 'onsale'}, 'spanMultipleDays': False}, 'classifications': [{'primary': True, 'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'name': 'Music'}, 'genre': {'id': 'KnvZfZ7vAeA', 'name': 'Rock'}, 'subGenre': {'id': 'KZazBEonSMnZfZ7v6F1', 'name': 'Pop'}, 'type': {'id': 'KZAyXgnZfZ7v7nI', 'name': 'Undefined'}, 'subType': {'id': 'KZFzBErXgnZfZ7v7lJ', 'name': 'Undefined'}, 'family': False}], 'promoter': {'id': '466', 'name': 'BOWERY PRESENTS', 'description': 'BOWERY PRESENTS / NTL / USA'}, 'promoters': [{'id': '466', 'name': 'BOWERY PRESENTS', 'description': 'BOWERY PRESENTS / NTL / USA'}], 'info': 'PLEASE NOTE: Pricing is all-in and includes fees (before taxes if applicable). By purchasing tickets to this event, you agree to abide by the health and safety measures in effect at the time of the event. Government mandates, venue protocols, and event requirements are subject to change. For more information, please search your event on msg.com. This event may have immersive elements, which may include flashing or strobe lights, intense lighting, visual effects, loud noises, smoke and/or fog. Such elements may aggravate certain medical or physical conditions, and guests should take this into consideration if they have a history of discomfort or physical symptoms when experiencing these elements.', 'pleaseNote': 'PLEASE NOTE: Pricing is all-in and includes fees (before taxes if applicable). $1 of every ticket sold will go towards the Alabama Shakes Fund which is built to provide much needed resources to nonprofits around the country who need it the most. Tickets are not available at the box office the first day of the public on sale. ARRIVE EARLY: Please arrive 60 minutes prior to showtime. All packages inspected prior to entry. By purchasing tickets, you agree to abide by the health and safety measures in effect at the time of the event. Government mandates, venue protocols, and event requirements subject to change. This event may have immersive elements, which may include flashing or strobe lights, intense lighting, visual effects, loud noises, smoke and/or fog. Such elements may aggravate certain medical or physical conditions, and guests should take into consideration if they have a history of discomfort or symptoms when experiencing these elements.', 'products': [{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'id': 'G5dYZ_Fnt633K', 'url': 'https://www.ticketmaster.com/spothero-radio-city-music-hall-new-york-new-york-09-02-2026/event/3C00648AA91D2493', 'type': 'Upsell', 'classifications': [{'primary': True, 'segment': {'id': 'KZFzniwnSyZfZ7v7n1', 'name': 'Miscellaneous'}, 'genre': {'id': 'KnvZfZ7v7ll', 'name': 'Undefined'}, 'subGenre': {'id': 'KZazBEonSMnZfZ7vAv1', 'name': 'Undefined'}, 'type': {'id': 'KZAyXgnZfZ7vAva', 'name': 'Parking'}, 'subType': {'id': 'KZFzBErXgnZfZ7vAFe', 'name': 'Regular'}, 'family': False}]}], 'seatmap': {'staticUrl': 'https://mapsapi.tmol.io/maps/geometry/3/event/3C0064887CE71349/staticImage?type=png&systemId=HOST'}, 'accessibility': {'ticketLimit': 2}, 'ticketLimit': {'info': 'There is a six (6) ticket limit for all presales and an eight (8) ticket limit for the public onsale.'}, 'ageRestrictions': {'legalAgeEnforced': False}, 'ticketing': {'safeTix': {'enabled': True}, 'allInclusivePricing': {'enabled': True}}, 'nameOrigin': 'custom', '_links': {'self': {'href': '/discovery/v2/events/G5dYZ_F-Hysua?locale=en-us'}, 'attractions': [{'href': '/discovery/v2/attractions/K8vZ9172Zc7?locale=en-us'}, {'href': '/discovery/v2/attractions/K8vZ9172BKV?locale=en-us'}], 'venues': [{'href': '/discovery/v2/venues/KovZpZAE7vdA?locale=en-us'}]}, '_embedded': {'venues': [{'name': 'Radio City Music Hall', 'type': 'venue', 'id': 'KovZpZAE7vdA', 'test': False, 'url': 'https://www.ticketmaster.com/radio-city-music-hall-tickets-new-york/venue/491523', 'locale': 'en-us', 'images': [{'ratio': '16_9', 'url': 'https://s1.ticketm.net/dbimages/23197v.jpg', 'width': 640, 'height': 360, 'fallback': False}], 'postalCode': '10020', 'timezone': 'America/New_York', 'city': {'name': 'New York'}, 'state': {'name': 'New York', 'stateCode': 'NY'}, 'country': {'name': 'United States Of America', 'countryCode': 'US'}, 'address': {'line1': '1260 6th Avenue'}, 'location': {'longitude': '-73.98039810', 'latitude': '40.75991360'}, 'markets': [{'name': 'New York/Tri-State Area', 'id': '35'}, {'name': 'All of US', 'id': '51'}, {'name': 'Northern New Jersey', 'id': '55'}, {'name': 'Connecticut', 'id': '124'}], 'dmas': [{'id': 200}, {'id': 296}, {'id': 345}, {'id': 422}], 'social': {'twitter': {'handle': '@Radiocity'}}, 'boxOfficeInfo': {'phoneNumberDetail': 'General Information (212) 247-4777 Group Sales (212) 465-6100', 'openHoursDetail': "Monday-Saturday: 12:00pm to 6:00pm * The Box Office will be open at 12:00pm daily or 60 minutes before the 1st performance of the day, whichever is earlier and will stay open until 6:00pm or 30 minutes after the last performance of the day begins, whichever is later. Sunday-Closed If an event takes place on Sunday, Box Office will open 60 minutes before the event start time and remain open 1 hour after event start time for Will Call and tickets sales for the evening's event only.", 'acceptedPaymentDetail': 'Cash, American Express, Visa, MasterCard', 'willCallDetail': 'Pick-up tickets anytime the day of the show during box office hours (see above). Customers must present the actual credit card used to place the order and a picture ID'}, 'parkingDetail': 'Local Parking Garages Rockefeller Center Garage - 48th St. between 5th & 6th Aves. 31 West 52nd St. - between 5th & 6th Aves. 51st St. Garage - 140 West 51st St. between 6th & 7th Aves. 7th Ave. Garage - 810 7th Ave. @ 52nd St. and Broadway 155 West 48th St. - between 6th & 7th Aves.', 'accessibleSeatingDetail': "RADIO CITY MUSIC HALL WHEELCHAIR AND TRANSFER SEATING POLICY: Wheelchair and Transfer seating is reserved exclusively for patrons with accessible needs and their companions. Accessible seating is intended for use by an individual with a mobility disability or other disability who requires the accessible features of accessible seating due to a disability, and that individuals companions. Radio City Music Hall reserves the right to investigate potential misuse of accessible seating and to take all appropriate action against individuals who fraudulently obtain tickets for accessible seating. While tickets for accessible seating legitimately purchased for the use of an individual with disability may be transferred to another individual under the same terms and conditions applicable to other tickets, in the event such ticket is transferred to a non-disabled individual, Radio City reserves the right to transfer that individual to other available seating TO ORDER WHEELCHAIR AND TRANSFER SEATING: Tickets for people with accessible needs, subject to availability, may be purchased in several ways: 1) Call Ticketmaster at 866-858-0008 2) Call Radio City Music Hall's Accessible Services Department at (212)465-6115. 3) Visit Radio City Music Hall's Box Office (see box office hours above 4) Order Online with Ticketmaster (select your event from the list to the left) For additional information regarding accessibility at Radio City Music Hall or to request any other accommodations, please call Radio City Music Hall's Disabled Services Department at (212) 465-6115 any weekday between 9:30am-4:30pm ET.", 'generalInfo': {'generalRule': 'ARRIVE EARLY: Please arrive one-hour prior to showtime. All packages, including briefcases and pocketbooks, will be inspected prior to entry. All patrons will continue to go through a screening process upon entry. As delays are expected, Radio City Entertainment requests that for all events, ticket holders arrive as early as possible. Guests are strongly discouraged from bringing packages, briefcases, knapsacks and video equipment to the Music Hall. No Smoking Allowed Anywhere in the venue No Recording Devices No Outside Food or Drink', 'childRule': 'Children two years of age or older require a ticket for admittance into any event held at Radio City Music Hall. For some performances, children under two will be admitted without a ticket however, they must sit on the lap of their parent or guardian. Please see specific show policies applicable to childrens admissions. Certain productions have different age requirements for tickets. Please see specific show for this information. For Barney shows, children 12 months and older are required to have a ticket.'}, 'upcomingEvents': {'ticketmaster': 278, '_total': 278, '_filtered': 0}, 'ada': {'adaPhones': "Ticketmaster:  (866) 858-0007    \nRadio City Music Hall's Accessible Services Department: (212)465-6115.", 'adaCustomCopy': 'RADIO CITY MUSIC HALL WHEELCHAIR AND TRANSFER SEATING POLICY:    \nWheelchair and Transfer seating is reserved exclusively for patrons with accessible needs and their companions. Only one Wheelchair or Transfer Seat(with one companion ticket) can be purchased per transaction. Any additional companion seats (Standard Admission) must be purchased in a separate transaction. \nAccessible seating (Wheelchair and Transfer) is reserved for the exclusive use of patrons with accessible needs and their companions and the purchase or use of these seating locations by  individuals that do not have accessible needs is strictly prohibited and can result in ejection and/or forfeiture of ticket price.    \n    \nImproper use of Wheelchair and Transfer seating locations by patrons without accessible needs is strictly prohibited and can result in revoked ticket privileges without refund. Only one Wheelchair  (wheelchair used as seat) or Transfer Seat  (wheelchair user transfers to actual seat) with one companion ticket can be purchased per transaction. Any additional companion seats must    \nbe purchased in a separate transaction using the Standard Admission.    \n    \nTO ORDER WHEELCHAIR AND TRANSFER SEATING:    \nTickets for people with accessible needs, subject to availability, may be purchased in several ways:    \n1) Call Ticketmaster at (866) 858-0007.    \n2) Call Radio City Music Hall\'s Accessible Services Department at (212)465-6115.    \n3) Visit Radio City Music Hall\'s Box Office.    \n4) Order Online - To order online:    \n   a) Press the "Back" button below to close this page.    \n      This will return you to the order form.    \n   b) When the order form is displayed, choose the type (Wheelchair, Transfer OR Standard Admission) and quantity of tickets you desire.    \n   c) Select the section and delivery method, then press the "Look for Tickets" button, then follow the\ninstructions displayed on each page.    \n    \n', 'adaHours': "For additional information regarding accessing Radio City Music Hall or to request any other accommodations, please call Radio City Music Hall's Accessible Services department at (212) 465-6115 any weekday between 9:30am-4:30pm.    \n"}, '_links': {'self': {'href': '/discovery/v2/venues/KovZpZAE7vdA?locale=en-us'}}}], 'attractions': [{'name': 'Alabama Shakes', 'type': 'attraction', 'id': 'K8vZ9172Zc7', 'test': False, 'url': 'https://www.ticketmaster.com/alabama-shakes-tickets/artist/1646903', 'locale': 'en-us', 'externalLinks': {'youtube': [{'url': 'https://www.youtube.com/user/AlabamaShakesVEVO'}], 'twitter': [{'url': 'https://twitter.com/alabama_shakes'}], 'itunes': [{'url': 'https://music.apple.com/us/artist/alabama-shakes/498509884'}], 'lastfm': [{'url': 'http://www.last.fm/music/Alabama+Shakes'}], 'spotify': [{'url': 'https://open.spotify.com/artist/16GcWuvvybAoaHr0NqT8Eh'}], 'wiki': [{'url': 'https://en.wikipedia.org/wiki/Alabama_Shakes'}], 'facebook': [{'url': 'https://www.facebook.com/theAlabamaShakes'}], 'instagram': [{'url': 'https://www.instagram.com/alabama_shakes/'}], 'musicbrainz': [{'id': '40419b33-18e9-4d5a-a674-30b4bb14bac2', 'url': 'https://musicbrainz.org/artist/40419b33-18e9-4d5a-a674-30b4bb14bac2'}], 'homepage': [{'url': 'http://www.alabamashakes.com/'}]}, 'images': [{'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_LANDSCAPE_16_9.jpg', 'width': 1136, 'height': 639, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_PORTRAIT_16_9.jpg', 'width': 640, 'height': 360, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_16_9.jpg', 'width': 1024, 'height': 576, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_ARTIST_PAGE_3_2.jpg', 'width': 305, 'height': 203, 'fallback': False}, {'ratio': '4_3', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_CUSTOM.jpg', 'width': 305, 'height': 225, 'fallback': False}, {'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_SOURCE', 'width': 2426, 'height': 1728, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_LARGE_16_9.jpg', 'width': 2048, 'height': 1152, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_PORTRAIT_3_2.jpg', 'width': 640, 'height': 427, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_3_2.jpg', 'width': 1024, 'height': 683, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_EVENT_DETAIL_PAGE_16_9.jpg', 'width': 205, 'height': 115, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RECOMENDATION_16_9.jpg', 'width': 100, 'height': 56, 'fallback': False}], 'classifications': [{'primary': True, 'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'name': 'Music'}, 'genre': {'id': 'KnvZfZ7vAeA', 'name': 'Rock'}, 'subGenre': {'id': 'KZazBEonSMnZfZ7v6F1', 'name': 'Pop'}, 'type': {'id': 'KZAyXgnZfZ7v7nI', 'name': 'Undefined'}, 'subType': {'id': 'KZFzBErXgnZfZ7v7lJ', 'name': 'Undefined'}, 'family': False}], 'upcomingEvents': {'tmr': 10, 'ticketmaster': 22, '_total': 32, '_filtered': 0}, '_links': {'self': {'href': '/discovery/v2/attractions/K8vZ9172Zc7?locale=en-us'}}}, {'name': 'Hannah Cohen', 'type': 'attraction', 'id': 'K8vZ9172BKV', 'test': False, 'url': 'https://www.ticketmaster.com/hannah-cohen-tickets/artist/1742807', 'locale': 'en-us', 'images': [{'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_EVENT_DETAIL_PAGE_16_9.jpg', 'width': 205, 'height': 115, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_RECOMENDATION_16_9.jpg', 'width': 100, 'height': 56, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_SOURCE', 'width': 2426, 'height': 1365, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_TABLET_LANDSCAPE_LARGE_16_9.jpg', 'width': 2048, 'height': 1152, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_ARTIST_PAGE_3_2.jpg', 'width': 305, 'height': 203, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_RETINA_PORTRAIT_3_2.jpg', 'width': 640, 'height': 427, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_RETINA_PORTRAIT_16_9.jpg', 'width': 640, 'height': 360, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_TABLET_LANDSCAPE_16_9.jpg', 'width': 1024, 'height': 576, 'fallback': False}, {'ratio': '16_9', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_RETINA_LANDSCAPE_16_9.jpg', 'width': 1136, 'height': 639, 'fallback': False}, {'ratio': '4_3', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_CUSTOM.jpg', 'width': 305, 'height': 225, 'fallback': False}, {'ratio': '3_2', 'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_TABLET_LANDSCAPE_3_2.jpg', 'wid

#### **API Interpretation** ####
<p> TicketMaster offers several APIs including Discovery (Public), Partner and Presence. <br>
We opted with Public API as this was the only suitable option for our case. However, one drawback is that it <br>
offers less visibility towards the company operations. We were initially looking to pull information on <br> 
the pricing structure. According to this [Reddit](https://www.reddit.com/r/programming/comments/10dxaiz/ticketmaster_stubhub_etc_inventory_via_api/) link, ticket platforms such as TicketMaster and Stubhub 
would be very unlikely to release coveted information related to their pricing as this would give its competitors an outside edge. 

Despite this setback, another possible next step, could be making another events API call to compare genre music preference of <br>
another city to see how they compared in popularity. 

</p>

In [12]:
# print(data['_embedded']['events'])

In [13]:
data['_embedded']['events']

[{'name': 'Alabama Shakes',
  'type': 'event',
  'id': 'G5dYZ_F-Hysua',
  'test': False,
  'url': 'https://www.ticketmaster.com/alabama-shakes-new-york-new-york-09-02-2026/event/3C0064887CE71349',
  'locale': 'en-us',
  'images': [{'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_SOURCE',
    'width': 2426,
    'height': 1728,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_LANDSCAPE_16_9.jpg',
    'width': 1136,
    'height': 639,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_PORTRAIT_16_9.jpg',
    'width': 640,
    'height': 360,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_LARGE_16_9.jpg',
    'width': 2048,
    'height': 1152,
    'fallback': False},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_PORTRAIT_3_2.jpg',
    'width': 640,
    'height': 427,
    'fallback': False},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_3_2.jpg',
    'width': 1024,
    'height': 683,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_16_9.jpg',
    'width': 1024,
    'height': 576,
    'fallback': False},
   {'ratio': '3_2',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_ARTIST_PAGE_3_2.jpg',
    'width': 305,
    'height': 203,
    'fallback': False},
   {'ratio': '4_3',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_CUSTOM.jpg',
    'width': 305,
    'height': 225,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_EVENT_DETAIL_PAGE_16_9.jpg',
    'width': 205,
    'height': 115,
    'fallback': False},
   {'ratio': '16_9',
    'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RECOMENDATION_16_9.jpg',
    'width': 100,
    'height': 56,
    'fallback': False}],
  'sales': {'public': {'startDateTime': '2026-04-17T14:00:00Z',
    'startTBD': False,
    'startTBA': False,
    'endDateTime': '2026-09-03T01:00:00Z'},
   'presales': [{'startDateTime': '2026-04-13T14:00:00Z',
     'endDateTime': '2026-04-17T03:59:00Z',
     'name': 'Citi® Cardmember Presale'},
    {'startDateTime': '2026-04-14T14:00:00Z',
     'endDateTime': '2026-04-17T03:59:00Z',
     'name': 'Artist Presale'},
    {'startDateTime': '2026-04-15T14:00:00Z',
     'endDateTime': '2026-04-17T03:59:00Z',
     'name': 'The Bowery Presents Presale'},
    {'startDateTime': '2026-04-15T14:00:00Z',
     'endDateTime': '2026-04-17T03:59:00Z',
     'name': 'Venue Presale'},
    {'startDateTime': '2026-04-17T14:00:00Z',
     'endDateTime': '2026-09-03T01:00:00Z',
     'name': 'Amex Reserved Tickets®'},
    {'startDateTime': '2026-04-17T14:00:00Z',
     'endDateTime': '2026-09-03T01:00:00Z',
     'name': 'Chase Cardholder Preferred Tickets'},
    {'startDateTime': '2026-04-17T14:00:00Z',
     'endDateTime': '2026-09-03T01:00:00Z',
     'name': 'Citi® Cardmember Preferred Tickets'},
    {'startDateTime': '2026-04-17T14:00:00Z',
     'endDateTime': '2026-05-18T14:00:00Z',
     'name': 'Verizon Access Featured Venues'},
    {'startDateTime': '2026-04-13T14:00:00Z',
     'endDateTime': '2026-04-17T03:59:00Z',
     'name': 'VIP Packages Presale'},
    {'startDateTime': '2026-04-17T14:00:00Z',
     'endDateTime': '2026-08-27T02:00:00Z',
     'name': 'VIP Packages'}]},
  'dates': {'start': {'localDate': '2026-09-02',
    'localTime': '20:00:00',
    'dateTime': '2026-09-03T00:00:00Z',
    'dateTBD': False,
    'dateTBA': False,
    'timeTBA': False,
    'noSpecificTime': False},
   'timezone': 'America/New_York',
   'status': {'code': 'onsale'},
   'spanMultipleDays': False},
  'classifications': [{'primary': True,
    'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'name': 'Music'},
    'genre': {'id': 'KnvZfZ7vAeA', 'name': 'Rock'},
    'subGenre': {'id': 'KZazBEonSMnZfZ7v6F1', 'name': 'Pop'},
    'type': {'id': 'KZAyXgnZfZ7v7nI', 'name': 'Undefined'},
    'subType': {'id': 'KZFzBErXgnZfZ7v7lJ', 'name': 'Undefined'},
    'family': False}],
  'promoter': {'id': '466',
   'name': 'BOWERY PRESENTS',
   'description': 'BOWERY PRESENTS / NTL / USA'},
  'promoters': [{'id': '466',
    'name': 'BOWERY PRESENTS',
    'description': 'BOWERY PRESENTS / NTL / USA'}],
  'info': 'PLEASE NOTE: Pricing is all-in and includes fees (before taxes if applicable). By purchasing tickets to this event, you agree to abide by the health and safety measures in effect at the time of the event. Government mandates, venue protocols, and event requirements are subject to change. For more information, please search your event on msg.com. This event may have immersive elements, which may include flashing or strobe lights, intense lighting, visual effects, loud noises, smoke and/or fog. Such elements may aggravate certain medical or physical conditions, and guests should take this into consideration if they have a history of discomfort or physical symptoms when experiencing these elements.',
  'pleaseNote': 'PLEASE NOTE: Pricing is all-in and includes fees (before taxes if applicable). $1 of every ticket sold will go towards the Alabama Shakes Fund which is built to provide much needed resources to nonprofits around the country who need it the most. Tickets are not available at the box office the first day of the public on sale. ARRIVE EARLY: Please arrive 60 minutes prior to showtime. All packages inspected prior to entry. By purchasing tickets, you agree to abide by the health and safety measures in effect at the time of the event. Government mandates, venue protocols, and event requirements subject to change. This event may have immersive elements, which may include flashing or strobe lights, intense lighting, visual effects, loud noises, smoke and/or fog. Such elements may aggravate certain medical or physical conditions, and guests should take into consideration if they have a history of discomfort or symptoms when experiencing these elements.',
  'products': [{'name': 'SPOTHERO RADIO CITY MUSIC HALL',
    'id': 'G5dYZ_Fnt633K',
    'url': 'https://www.ticketmaster.com/spothero-radio-city-music-hall-new-york-new-york-09-02-2026/event/3C00648AA91D2493',
    'type': 'Upsell',
    'classifications': [{'primary': True,
      'segment': {'id': 'KZFzniwnSyZfZ7v7n1', 'name': 'Miscellaneous'},
      'genre': {'id': 'KnvZfZ7v7ll', 'name': 'Undefined'},
      'subGenre': {'id': 'KZazBEonSMnZfZ7vAv1', 'name': 'Undefined'},
      'type': {'id': 'KZAyXgnZfZ7vAva', 'name': 'Parking'},
      'subType': {'id': 'KZFzBErXgnZfZ7vAFe', 'name': 'Regular'},
      'family': False}]}],
  'seatmap': {'staticUrl': 'https://mapsapi.tmol.io/maps/geometry/3/event/3C0064887CE71349/staticImage?type=png&systemId=HOST'},
  'accessibility': {'ticketLimit': 2},
  'ticketLimit': {'info': 'There is a six (6) ticket limit for all presales and an eight (8) ticket limit for the public onsale.'},
  'ageRestrictions': {'legalAgeEnforced': False},
  'ticketing': {'safeTix': {'enabled': True},
   'allInclusivePricing': {'enabled': True}},
  'nameOrigin': 'custom',
  '_links': {'self': {'href': '/discovery/v2/events/G5dYZ_F-Hysua?locale=en-us'},
   'attractions': [{'href': '/discovery/v2/attractions/K8vZ9172Zc7?locale=en-us'},
    {'href': '/discovery/v2/attractions/K8vZ9172BKV?locale=en-us'}],
   'venues': [{'href': '/discovery/v2/venues/KovZpZAE7vdA?locale=en-us'}]},
  '_embedded': {'venues': [{'name': 'Radio City Music Hall',
     'type': 'venue',
     'id': 'KovZpZAE7vdA',
     'test': False,
     'url': 'https://www.ticketmaster.com/radio-city-music-hall-tickets-new-york/venue/491523',
     'locale': 'en-us',
     'images': [{'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dbimages/23197v.jpg',
       'width': 640,
       'height': 360,
       'fallback': False}],
     'postalCode': '10020',
     'timezone': 'America/New_York',
     'city': {'name': 'New York'},
     'state': {'name': 'New York', 'stateCode': 'NY'},
     'country': {'name': 'United States Of America', 'countryCode': 'US'},
     'address': {'line1': '1260 6th Avenue'},
     'location': {'longitude': '-73.98039810', 'latitude': '40.75991360'},
     'markets': [{'name': 'New York/Tri-State Area', 'id': '35'},
      {'name': 'All of US', 'id': '51'},
      {'name': 'Northern New Jersey', 'id': '55'},
      {'name': 'Connecticut', 'id': '124'}],
     'dmas': [{'id': 200}, {'id': 296}, {'id': 345}, {'id': 422}],
     'social': {'twitter': {'handle': '@Radiocity'}},
     'boxOfficeInfo': {'phoneNumberDetail': 'General Information (212) 247-4777 Group Sales (212) 465-6100',
      'openHoursDetail': "Monday-Saturday: 12:00pm to 6:00pm * The Box Office will be open at 12:00pm daily or 60 minutes before the 1st performance of the day, whichever is earlier and will stay open until 6:00pm or 30 minutes after the last performance of the day begins, whichever is later. Sunday-Closed If an event takes place on Sunday, Box Office will open 60 minutes before the event start time and remain open 1 hour after event start time for Will Call and tickets sales for the evening's event only.",
      'acceptedPaymentDetail': 'Cash, American Express, Visa, MasterCard',
      'willCallDetail': 'Pick-up tickets anytime the day of the show during box office hours (see above). Customers must present the actual credit card used to place the order and a picture ID'},
     'parkingDetail': 'Local Parking Garages Rockefeller Center Garage - 48th St. between 5th & 6th Aves. 31 West 52nd St. - between 5th & 6th Aves. 51st St. Garage - 140 West 51st St. between 6th & 7th Aves. 7th Ave. Garage - 810 7th Ave. @ 52nd St. and Broadway 155 West 48th St. - between 6th & 7th Aves.',
     'accessibleSeatingDetail': "RADIO CITY MUSIC HALL WHEELCHAIR AND TRANSFER SEATING POLICY: Wheelchair and Transfer seating is reserved exclusively for patrons with accessible needs and their companions. Accessible seating is intended for use by an individual with a mobility disability or other disability who requires the accessible features of accessible seating due to a disability, and that individuals companions. Radio City Music Hall reserves the right to investigate potential misuse of accessible seating and to take all appropriate action against individuals who fraudulently obtain tickets for accessible seating. While tickets for accessible seating legitimately purchased for the use of an individual with disability may be transferred to another individual under the same terms and conditions applicable to other tickets, in the event such ticket is transferred to a non-disabled individual, Radio City reserves the right to transfer that individual to other available seating TO ORDER WHEELCHAIR AND TRANSFER SEATING: Tickets for people with accessible needs, subject to availability, may be purchased in several ways: 1) Call Ticketmaster at 866-858-0008 2) Call Radio City Music Hall's Accessible Services Department at (212)465-6115. 3) Visit Radio City Music Hall's Box Office (see box office hours above 4) Order Online with Ticketmaster (select your event from the list to the left) For additional information regarding accessibility at Radio City Music Hall or to request any other accommodations, please call Radio City Music Hall's Disabled Services Department at (212) 465-6115 any weekday between 9:30am-4:30pm ET.",
     'generalInfo': {'generalRule': 'ARRIVE EARLY: Please arrive one-hour prior to showtime. All packages, including briefcases and pocketbooks, will be inspected prior to entry. All patrons will continue to go through a screening process upon entry. As delays are expected, Radio City Entertainment requests that for all events, ticket holders arrive as early as possible. Guests are strongly discouraged from bringing packages, briefcases, knapsacks and video equipment to the Music Hall. No Smoking Allowed Anywhere in the venue No Recording Devices No Outside Food or Drink',
      'childRule': 'Children two years of age or older require a ticket for admittance into any event held at Radio City Music Hall. For some performances, children under two will be admitted without a ticket however, they must sit on the lap of their parent or guardian. Please see specific show policies applicable to childrens admissions. Certain productions have different age requirements for tickets. Please see specific show for this information. For Barney shows, children 12 months and older are required to have a ticket.'},
     'upcomingEvents': {'ticketmaster': 278, '_total': 278, '_filtered': 0},
     'ada': {'adaPhones': "Ticketmaster:  (866) 858-0007    \nRadio City Music Hall's Accessible Services Department: (212)465-6115.",
      'adaCustomCopy': 'RADIO CITY MUSIC HALL WHEELCHAIR AND TRANSFER SEATING POLICY:    \nWheelchair and Transfer seating is reserved exclusively for patrons with accessible needs and their companions. Only one Wheelchair or Transfer Seat(with one companion ticket) can be purchased per transaction. Any additional companion seats (Standard Admission) must be purchased in a separate transaction. \nAccessible seating (Wheelchair and Transfer) is reserved for the exclusive use of patrons with accessible needs and their companions and the purchase or use of these seating locations by  individuals that do not have accessible needs is strictly prohibited and can result in ejection and/or forfeiture of ticket price.    \n    \nImproper use of Wheelchair and Transfer seating locations by patrons without accessible needs is strictly prohibited and can result in revoked ticket privileges without refund. Only one Wheelchair  (wheelchair used as seat) or Transfer Seat  (wheelchair user transfers to actual seat) with one companion ticket can be purchased per transaction. Any additional companion seats must    \nbe purchased in a separate transaction using the Standard Admission.    \n    \nTO ORDER WHEELCHAIR AND TRANSFER SEATING:    \nTickets for people with accessible needs, subject to availability, may be purchased in several ways:    \n1) Call Ticketmaster at (866) 858-0007.    \n2) Call Radio City Music Hall\'s Accessible Services Department at (212)465-6115.    \n3) Visit Radio City Music Hall\'s Box Office.    \n4) Order Online - To order online:    \n   a) Press the "Back" button below to close this page.    \n      This will return you to the order form.    \n   b) When the order form is displayed, choose the type (Wheelchair, Transfer OR Standard Admission) and quantity of tickets you desire.    \n   c) Select the section and delivery method, then press the "Look for Tickets" button, then follow the\ninstructions displayed on each page.    \n    \n',
      'adaHours': "For additional information regarding accessing Radio City Music Hall or to request any other accommodations, please call Radio City Music Hall's Accessible Services department at (212) 465-6115 any weekday between 9:30am-4:30pm.    \n"},
     '_links': {'self': {'href': '/discovery/v2/venues/KovZpZAE7vdA?locale=en-us'}}}],
   'attractions': [{'name': 'Alabama Shakes',
     'type': 'attraction',
     'id': 'K8vZ9172Zc7',
     'test': False,
     'url': 'https://www.ticketmaster.com/alabama-shakes-tickets/artist/1646903',
     'locale': 'en-us',
     'externalLinks': {'youtube': [{'url': 'https://www.youtube.com/user/AlabamaShakesVEVO'}],
      'twitter': [{'url': 'https://twitter.com/alabama_shakes'}],
      'itunes': [{'url': 'https://music.apple.com/us/artist/alabama-shakes/498509884'}],
      'lastfm': [{'url': 'http://www.last.fm/music/Alabama+Shakes'}],
      'spotify': [{'url': 'https://open.spotify.com/artist/16GcWuvvybAoaHr0NqT8Eh'}],
      'wiki': [{'url': 'https://en.wikipedia.org/wiki/Alabama_Shakes'}],
      'facebook': [{'url': 'https://www.facebook.com/theAlabamaShakes'}],
      'instagram': [{'url': 'https://www.instagram.com/alabama_shakes/'}],
      'musicbrainz': [{'id': '40419b33-18e9-4d5a-a674-30b4bb14bac2',
        'url': 'https://musicbrainz.org/artist/40419b33-18e9-4d5a-a674-30b4bb14bac2'}],
      'homepage': [{'url': 'http://www.alabamashakes.com/'}]},
     'images': [{'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_LANDSCAPE_16_9.jpg',
       'width': 1136,
       'height': 639,
       'fallback': False},
      {'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_PORTRAIT_16_9.jpg',
       'width': 640,
       'height': 360,
       'fallback': False},
      {'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_16_9.jpg',
       'width': 1024,
       'height': 576,
       'fallback': False},
      {'ratio': '3_2',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_ARTIST_PAGE_3_2.jpg',
       'width': 305,
       'height': 203,
       'fallback': False},
      {'ratio': '4_3',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_CUSTOM.jpg',
       'width': 305,
       'height': 225,
       'fallback': False},
      {'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_SOURCE',
       'width': 2426,
       'height': 1728,
       'fallback': False},
      {'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_LARGE_16_9.jpg',
       'width': 2048,
       'height': 1152,
       'fallback': False},
      {'ratio': '3_2',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RETINA_PORTRAIT_3_2.jpg',
       'width': 640,
       'height': 427,
       'fallback': False},
      {'ratio': '3_2',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_TABLET_LANDSCAPE_3_2.jpg',
       'width': 1024,
       'height': 683,
       'fallback': False},
      {'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_EVENT_DETAIL_PAGE_16_9.jpg',
       'width': 205,
       'height': 115,
       'fallback': False},
      {'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/359/ad509b7f-2b54-407f-9d04-9dbbf11fb359_RECOMENDATION_16_9.jpg',
       'width': 100,
       'height': 56,
       'fallback': False}],
     'classifications': [{'primary': True,
       'segment': {'id': 'KZFzniwnSyZfZ7v7nJ', 'name': 'Music'},
       'genre': {'id': 'KnvZfZ7vAeA', 'name': 'Rock'},
       'subGenre': {'id': 'KZazBEonSMnZfZ7v6F1', 'name': 'Pop'},
       'type': {'id': 'KZAyXgnZfZ7v7nI', 'name': 'Undefined'},
       'subType': {'id': 'KZFzBErXgnZfZ7v7lJ', 'name': 'Undefined'},
       'family': False}],
     'upcomingEvents': {'tmr': 10,
      'ticketmaster': 22,
      '_total': 32,
      '_filtered': 0},
     '_links': {'self': {'href': '/discovery/v2/attractions/K8vZ9172Zc7?locale=en-us'}}},
    {'name': 'Hannah Cohen',
     'type': 'attraction',
     'id': 'K8vZ9172BKV',
     'test': False,
     'url': 'https://www.ticketmaster.com/hannah-cohen-tickets/artist/1742807',
     'locale': 'en-us',
     'images': [{'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_EVENT_DETAIL_PAGE_16_9.jpg',
       'width': 205,
       'height': 115,
       'fallback': False},
      {'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_RECOMENDATION_16_9.jpg',
       'width': 100,
       'height': 56,
       'fallback': False},
      {'ratio': '16_9',
       'url': 'https://s1.ticketm.net/dam/a/73d/27af866c-132e-44af-9a23-4479b20ac73d_SOURCE',

### Creating initial dataframe for data exploration ### 
This dataframe gives us 20 row view

In [14]:
df = pd.DataFrame(data['_embedded']['events'])
df

,name,type,id,test,url,locale,images,sales,dates,classifications,...,pleaseNote,products,seatmap,accessibility,ticketLimit,ageRestrictions,ticketing,nameOrigin,_links,_embedded
0,Alabama Shakes,event,G5dYZ_F-Hysua,False,https://www.ticketmaster.com/alabama-shakes-ne...,en-us,[{'url': 'https://s1.ticketm.net/dam/a/359/ad5...,{'public': {'startDateTime': '2026-04-17T14:00...,"{'start': {'localDate': '2026-09-02', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
1,YUNGBLUD: IDOLS - THE WORLD TOUR,event,G5dYZbVkK6OTg,False,https://www.ticketmaster.com/yungblud-idols-th...,en-us,"[{'ratio': '4_3', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2025-10-08T14:00...,"{'start': {'localDate': '2026-06-10', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a four (4) ticket limit for...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZb...,"{'venues': [{'name': 'Radio City Music Hall', ..."
2,Khalid: It's Always Summer Somewhere Tour,event,G5dYZbzhrO0M1,False,https://www.ticketmaster.com/khalid-its-always...,en-us,"[{'ratio': '4_3', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2025-12-12T15:00...,"{'start': {'localDate': '2026-06-12', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is an eight (8) ticket limit f...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZb...,"{'venues': [{'name': 'Radio City Music Hall', ..."
3,Jessie Ware: The Superbloom Tour,event,G5dYZ_kma1OTc,False,https://www.ticketmaster.com/jessie-ware-the-s...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-04-23T13:00...,"{'start': {'localDate': '2026-10-08', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
4,Mon Laferte - Femme Fatale Tour,event,G5dYZ_kppZOWi,False,https://www.ticketmaster.com/mon-laferte-femme...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-03-27T14:00...,"{'start': {'localDate': '2026-08-22', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
5,The Format - 20 Years of Dog Problems + New & ...,event,G5dYZ_1NSz3fJ,False,https://www.ticketmaster.com/the-format-20-yea...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-05-20T16:00...,"{'start': {'localDate': '2026-10-09', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a four (4) ticket limit for...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
6,The Human League With Very Special Guests Soft...,event,G5dYZ_eBH0oca,False,https://www.ticketmaster.com/the-human-league-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-01-23T15:00...,"{'start': {'localDate': '2026-06-26', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
7,Shaboozey - Outlaws Never Die Tour,event,G5dYZ_aJgQsbY,False,https://www.ticketmaster.com/shaboozey-outlaws...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-05-01T14:00...,"{'start': {'localDate': '2026-10-03', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a four (4) ticket limit for...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
8,Ricardo Montaner: El Último Regreso Tour,event,G5dYZbUCqm3ey,False,https://www.ticketmaster.com/ricardo-montaner-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2025-11-14T15:00...,"{'start': {'localDate': '2026-09-03', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is an eight (8) ticket limit f...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZb...,"{'venues': [{'name': 'Radio City Music Hall', ..."
9,Ella Mai: Do You Still Love Me? Tour,event,G5dYZ_kh9-o_2,False,https://www.ticketmaster.com/ella-mai-do-you-s...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-03-20T14:00...,"{'start': {'localDate': '2026-08-28', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
10,CA7RIEL & Paco Amoroso: FREE SPIRITS WORLD TOUR,event,G5dYZ_69VFek3,False,https://www.ticketmaster.com/ca7riel-paco-amor...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-03-27T14:00...,"{'start': {'localDate': '2026-06-19', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
11,Ray LaMontagne - Trouble 20th Anniversary Tour,event,G5diZb0wXAsJO,False,https://www.ticketmaster.com/ray-lamontagne-tr...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2025-03-21T14:00...,"{'start': {'localDate': '2026-10-01', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is a six (6) ticket limit per ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZb...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
12,Ray LaMontagne - Trouble 20th Anniversary Tour,event,G5diZb0wX6-JP,False,https://www.ticketmaster.com/ray-lamontagne-tr...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2025-03-21T14:00...,"{'start': {'localDate': '2026-10-02', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is a six (6) ticket limit per ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZb...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
13,Ray LaMontagne - Trouble 20th Anniversary Tour,event,G5diZb0wXCoJw,False,https://www.ticketmaster.com/ray-lamontagne-tr...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2025-03-21T14:00...,"{'start': {'localDate': '2026-10-03', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is a six (6) ticket limit per ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZb...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
14,THE CHICKS - TAKING THE LONG WAY,event,G5diZ_5nf9esr,False,https://www.ticketmaster.com/the-chicks-taking...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-06-04T14:00...,"{'start': {'localDate': '2026-10-12', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is a four (4) ticket limit per...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
15,THE CHICKS - TAKING THE LONG WAY,event,G5diZ_5nf_3sx,False,https://www.ticketmaster.com/the-chicks-taking...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-06-04T14:00...,"{'start': {'localDate': '2026-10-13', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is a four (4) ticket limit per...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
16,Tom Jones: Come Gather Round Tour,event,G5diZ_5p0DSJ6,False,https://www.ticketmaster.com/tom-jones-come-ga...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-05-29T14:00...,"{'start': {'localDate': '2026-09-29', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is an eight (8) ticket limit p...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
17,Tom Jones: Come Gather Round Tour,event,G5diZ_5pPZNJ4,False,https://www.ticketmaster.com/tom-jones-come-ga...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-05-29T14:00...,"{'start': {'localDate': '2026-09-30', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is an eight (8) ticket limit p...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
18,SatchVai Band Ft Joe Satriani & Steve Vai with...,event,G5diZbzpp0K6u,False,https://www.ticketmaster.com/satchvai-band-ft-...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2025-12-12T15:00...,"{'start': {'localDate': '2026-05-28', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,[{'name': 'SatchVai Band VIP Upgrade Experienc...,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is an eight (8) ticket limit p...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZb...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
19,An Evening With Lucinda Williams and Her Band,event,G5diZ_kM3NA-3,False,https://www.ticketmaster.com/an-evening-with-l...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-03-20T14:00...,"{'start': {'localDate': '2026-05-29', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,"Unfortunately, the Event Organizer has had to ...","[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,{'ticketLimit': 4},{'info': 'There is a four (4) ticket limit per...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."

<p> Looking at the 20 rows of data with <code>df.info</code>, we see that all the columns are populated with some values.
It does not appear that we have any missing data at this point.</p>

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             20 non-null     str
 1   type             20 non-null     str
 2   id               20 non-null     str
 3   test             20 non-null     bool
 4   url              20 non-null     str
 5   locale           20 non-null     str
 6   images           20 non-null     object
 7   sales            20 non-null     object
 8   dates            20 non-null     object
 9   classifications  20 non-null     object
 10  promoter         20 non-null     object
 11  promoters        20 non-null     object
 12  info             20 non-null     str
 13  pleaseNote       20 non-null     str
 14  products         20 non-null     object
 15  seatmap          20 non-null     object
 16  accessibility    20 non-null     object
 17  ticketLimit      20 non-null     object
 18  ageRestrictions  20 non-null     object
 19  ticketing        20 non-null     object
 20  nameOrigin       20 non-null     str
 21  _links           20 non-null     object
 22  _embedded        20 non-null     object
dtypes: bool(1), object(14), str(8)
memory usage: 39.3+ KB

#### Some columns in the Dataframe are not in a usable state. So, I'm starting to set the stage to start looping within `Accessibility`, `Products`, `Classifications` and `Venue` name. ####

In [16]:
accessibility = df['accessibility']
accessibility.iloc[13]

{'ticketLimit': 4}

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             20 non-null     str
 1   type             20 non-null     str
 2   id               20 non-null     str
 3   test             20 non-null     bool
 4   url              20 non-null     str
 5   locale           20 non-null     str
 6   images           20 non-null     object
 7   sales            20 non-null     object
 8   dates            20 non-null     object
 9   classifications  20 non-null     object
 10  promoter         20 non-null     object
 11  promoters        20 non-null     object
 12  info             20 non-null     str
 13  pleaseNote       20 non-null     str
 14  products         20 non-null     object
 15  seatmap          20 non-null     object
 16  accessibility    20 non-null     object
 17  ticketLimit      20 non-null     object
 18  ageRestrictions  20 non-null     object
 19  ticketing        20 non-null     object
 20  nameOrigin       20 non-null     str
 21  _links           20 non-null     object
 22  _embedded        20 non-null     object
dtypes: bool(1), object(14), str(8)
memory usage: 39.3+ KB

### For-loop to grab the value of Accessibility in nested dictionary encased in a list ###

In [18]:
for item in accessibility:
    for location, value in item.items():
        print(f'Ticket Limit: ',value)

Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  2
Ticket Limit:  4
Ticket Limit:  4
Ticket Limit:  4
Ticket Limit:  4
Ticket Limit:  4
Ticket Limit:  4
Ticket Limit:  4
Ticket Limit:  4
Ticket Limit:  4

### Creating variable to refer to 'products' column ###

In [19]:
product_name = df['products']

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             20 non-null     str
 1   type             20 non-null     str
 2   id               20 non-null     str
 3   test             20 non-null     bool
 4   url              20 non-null     str
 5   locale           20 non-null     str
 6   images           20 non-null     object
 7   sales            20 non-null     object
 8   dates            20 non-null     object
 9   classifications  20 non-null     object
 10  promoter         20 non-null     object
 11  promoters        20 non-null     object
 12  info             20 non-null     str
 13  pleaseNote       20 non-null     str
 14  products         20 non-null     object
 15  seatmap          20 non-null     object
 16  accessibility    20 non-null     object
 17  ticketLimit      20 non-null     object
 18  ageRestrictions  20 non-null     object
 19  ticketing        20 non-null     object
 20  nameOrigin       20 non-null     str
 21  _links           20 non-null     object
 22  _embedded        20 non-null     object
dtypes: bool(1), object(14), str(8)
memory usage: 39.3+ KB

### Creating for loop to grab value of PRODUCTS column ###

In [21]:
for item in product_name:
    for n in item:
        print(n['name'])

SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO RADIO CITY MUSIC HALL
SPOTHERO BEACON THEATRE
SPOTHERO BEACON THEATRE
SPOTHERO BEACON THEATRE
SPOTHERO BEACON THEATRE
SPOTHERO BEACON THEATRE
SPOTHERO BEACON THEATRE
SPOTHERO BEACON THEATRE
SatchVai Band VIP Upgrade Experience (No Ticket Included)
SPOTHERO BEACON THEATRE
SPOTHERO BEACON THEATRE

### Re-assigning the output of above for-loop to PRODUCTS column to reflect new changes. ###

In [22]:
df['products'] = n['name']

### List comprehension using for loop and re-assigning value to Accessibility column ###

In [23]:
df['accessibility'] = [f'Ticket Limit: {value}'
                       for item in accessibility
                        for location, value in item.items()]

# list comprehension to loop the 'accessibility' column to get Ticket Limit dictionary.

##### Renaming columns to something that is more meaningful #####

In [24]:
df.rename(columns={
    '_embedded': 'Venue Name', 
    'name': 'Name',
    'type': 'Type', 
    'id': 'ID',
    'products': 'PRODUCTS', 
    'accessibility': 'Accessibility',
    'classifications': 'Genre'

    }, inplace=True)

In [25]:
df

,Name,Type,ID,test,url,locale,images,sales,dates,Genre,...,pleaseNote,PRODUCTS,seatmap,Accessibility,ticketLimit,ageRestrictions,ticketing,nameOrigin,_links,Venue Name
0,Alabama Shakes,event,G5dYZ_F-Hysua,False,https://www.ticketmaster.com/alabama-shakes-ne...,en-us,[{'url': 'https://s1.ticketm.net/dam/a/359/ad5...,{'public': {'startDateTime': '2026-04-17T14:00...,"{'start': {'localDate': '2026-09-02', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
1,YUNGBLUD: IDOLS - THE WORLD TOUR,event,G5dYZbVkK6OTg,False,https://www.ticketmaster.com/yungblud-idols-th...,en-us,"[{'ratio': '4_3', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2025-10-08T14:00...,"{'start': {'localDate': '2026-06-10', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a four (4) ticket limit for...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZb...,"{'venues': [{'name': 'Radio City Music Hall', ..."
2,Khalid: It's Always Summer Somewhere Tour,event,G5dYZbzhrO0M1,False,https://www.ticketmaster.com/khalid-its-always...,en-us,"[{'ratio': '4_3', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2025-12-12T15:00...,"{'start': {'localDate': '2026-06-12', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is an eight (8) ticket limit f...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZb...,"{'venues': [{'name': 'Radio City Music Hall', ..."
3,Jessie Ware: The Superbloom Tour,event,G5dYZ_kma1OTc,False,https://www.ticketmaster.com/jessie-ware-the-s...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-04-23T13:00...,"{'start': {'localDate': '2026-10-08', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
4,Mon Laferte - Femme Fatale Tour,event,G5dYZ_kppZOWi,False,https://www.ticketmaster.com/mon-laferte-femme...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-03-27T14:00...,"{'start': {'localDate': '2026-08-22', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
5,The Format - 20 Years of Dog Problems + New & ...,event,G5dYZ_1NSz3fJ,False,https://www.ticketmaster.com/the-format-20-yea...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-05-20T16:00...,"{'start': {'localDate': '2026-10-09', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a four (4) ticket limit for...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
6,The Human League With Very Special Guests Soft...,event,G5dYZ_eBH0oca,False,https://www.ticketmaster.com/the-human-league-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-01-23T15:00...,"{'start': {'localDate': '2026-06-26', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
7,Shaboozey - Outlaws Never Die Tour,event,G5dYZ_aJgQsbY,False,https://www.ticketmaster.com/shaboozey-outlaws...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-05-01T14:00...,"{'start': {'localDate': '2026-10-03', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a four (4) ticket limit for...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
8,Ricardo Montaner: El Último Regreso Tour,event,G5dYZbUCqm3ey,False,https://www.ticketmaster.com/ricardo-montaner-...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2025-11-14T15:00...,"{'start': {'localDate': '2026-09-03', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is an eight (8) ticket limit f...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZb...,"{'venues': [{'name': 'Radio City Music Hall', ..."
9,Ella Mai: Do You Still Love Me? Tour,event,G5dYZ_kh9-o_2,False,https://www.ticketmaster.com/ella-mai-do-you-s...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-03-20T14:00...,"{'start': {'localDate': '2026-08-28', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
10,CA7RIEL & Paco Amoroso: FREE SPIRITS WORLD TOUR,event,G5dYZ_69VFek3,False,https://www.ticketmaster.com/ca7riel-paco-amor...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-03-27T14:00...,"{'start': {'localDate': '2026-06-19', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 2,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ..."
11,Ray LaMontagne - Trouble 20th Anniversary Tour,event,G5diZb0wXAsJO,False,https://www.ticketmaster.com/ray-lamontagne-tr...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2025-03-21T14:00...,"{'start': {'localDate': '2026-10-01', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is a six (6) ticket limit per ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZb...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
12,Ray LaMontagne - Trouble 20th Anniversary Tour,event,G5diZb0wX6-JP,False,https://www.ticketmaster.com/ray-lamontagne-tr...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2025-03-21T14:00...,"{'start': {'localDate': '2026-10-02', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is a six (6) ticket limit per ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZb...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
13,Ray LaMontagne - Trouble 20th Anniversary Tour,event,G5diZb0wXCoJw,False,https://www.ticketmaster.com/ray-lamontagne-tr...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2025-03-21T14:00...,"{'start': {'localDate': '2026-10-03', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is a six (6) ticket limit per ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZb...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
14,THE CHICKS - TAKING THE LONG WAY,event,G5diZ_5nf9esr,False,https://www.ticketmaster.com/the-chicks-taking...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-06-04T14:00...,"{'start': {'localDate': '2026-10-12', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is a four (4) ticket limit per...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
15,THE CHICKS - TAKING THE LONG WAY,event,G5diZ_5nf_3sx,False,https://www.ticketmaster.com/the-chicks-taking...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-06-04T14:00...,"{'start': {'localDate': '2026-10-13', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is a four (4) ticket limit per...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
16,Tom Jones: Come Gather Round Tour,event,G5diZ_5p0DSJ6,False,https://www.ticketmaster.com/tom-jones-come-ga...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-05-29T14:00...,"{'start': {'localDate': '2026-09-29', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is an eight (8) ticket limit p...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
17,Tom Jones: Come Gather Round Tour,event,G5diZ_5pPZNJ4,False,https://www.ticketmaster.com/tom-jones-come-ga...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-05-29T14:00...,"{'start': {'localDate': '2026-09-30', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is an eight (8) ticket limit p...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
18,SatchVai Band Ft Joe Satriani & Steve Vai with...,event,G5diZbzpp0K6u,False,https://www.ticketmaster.com/satchvai-band-ft-...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2025-12-12T15:00...,"{'start': {'localDate': '2026-05-28', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,PLEASE NOTE: Pricing is all-in and includes fe...,SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is an eight (8) ticket limit p...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZb...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."
19,An Evening With Lucinda Williams and Her Band,event,G5diZ_kM3NA-3,False,https://www.ticketmaster.com/an-evening-with-l...,en-us,"[{'ratio': '3_2', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2026-03-20T14:00...,"{'start': {'localDate': '2026-05-29', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,"Unfortunately, the Event Organizer has had to ...",SPOTHERO BEACON THEATRE,{'staticUrl': 'https://mapsapi.tmol.io/maps/ge...,Ticket Limit: 4,{'info': 'There is a four (4) ticket limit per...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5diZ_...,"{'venues': [{'name': 'Beacon Theatre', 'type':..."

#### Creating variable to 'Genre' column ####

In [26]:
genre = df['Genre']
genre

0     [{'primary': True, 'segment': {'id': 'KZFzniwn...
1     [{'primary': True, 'segment': {'id': 'KZFzniwn...
2     [{'primary': True, 'segment': {'id': 'KZFzniwn...
3     [{'primary': True, 'segment': {'id': 'KZFzniwn...
4     [{'primary': True, 'segment': {'id': 'KZFzniwn...
5     [{'primary': True, 'segment': {'id': 'KZFzniwn...
6     [{'primary': True, 'segment': {'id': 'KZFzniwn...
7     [{'primary': True, 'segment': {'id': 'KZFzniwn...
8     [{'primary': True, 'segment': {'id': 'KZFzniwn...
9     [{'primary': True, 'segment': {'id': 'KZFzniwn...
10    [{'primary': True, 'segment': {'id': 'KZFzniwn...
11    [{'primary': True, 'segment': {'id': 'KZFzniwn...
12    [{'primary': True, 'segment': {'id': 'KZFzniwn...
13    [{'primary': True, 'segment': {'id': 'KZFzniwn...
14    [{'primary': True, 'segment': {'id': 'KZFzniwn...
15    [{'primary': True, 'segment': {'id': 'KZFzniwn...
16    [{'primary': True, 'segment': {'id': 'KZFzniwn...
17    [{'primary': True, 'segment': {'id': 'KZFzniwn...
18    [{'primary': True, 'segment': {'id': 'KZFzniwn...
19    [{'primary': True, 'segment': {'id': 'KZFzniwn...
Name: Genre, dtype: object

#### For loop to pull Genre name out of dictionary list ####

In [27]:
for x in genre: #x is the dictionary
    for item in x:
        print(item['genre']['name']) #loop through Genre list to pull Genre name.

Rock
Rock
R&B
Rock
Pop
Rock
Rock
Country
Latin
R&B
Latin
Rock
Rock
Rock
Country
Country
Rock
Rock
Rock
Rock

#### list comprehension using for loop and re-assigning the value to 'Genre' column ####

In [28]:
df['Genre'] = [item['genre']['name'] 
                for x in genre
                for item in x]

#### Creating variable for 'Venue Name' ####

In [29]:
venue_name = df['Venue Name']

#### For loop to grab the venue name from dictionary in a list ####

In [30]:
for x in venue_name: # to loop through Venue Name
    for y in x['venues']:
        print(y['name'])

Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Radio City Music Hall
Beacon Theatre
Beacon Theatre
Beacon Theatre
Beacon Theatre
Beacon Theatre
Beacon Theatre
Beacon Theatre
Beacon Theatre
Beacon Theatre

#### List comprehension using for loop and reassigning the value back to 'Venue Name' column. ####

In [31]:
df['Venue Name'] = [y['name'] 
                    for x in venue_name
                    for y in x['venues']]

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             20 non-null     str
 1   Type             20 non-null     str
 2   ID               20 non-null     str
 3   test             20 non-null     bool
 4   url              20 non-null     str
 5   locale           20 non-null     str
 6   images           20 non-null     object
 7   sales            20 non-null     object
 8   dates            20 non-null     object
 9   Genre            20 non-null     str
 10  promoter         20 non-null     object
 11  promoters        20 non-null     object
 12  info             20 non-null     str
 13  pleaseNote       20 non-null     str
 14  PRODUCTS         20 non-null     str
 15  seatmap          20 non-null     object
 16  Accessibility    20 non-null     str
 17  ticketLimit      20 non-null     object
 18  ageRestrictions  20 non-null     object
 19  ticketing        20 non-null     object
 20  nameOrigin       20 non-null     str
 21  _links           20 non-null     object
 22  Venue Name       20 non-null     str
dtypes: bool(1), object(10), str(12)
memory usage: 40.5+ KB

##### Pagination Function #####
<p>Here, we're implementing a function <code>getAllPages()</code> for pagination, in order to retrieve additional pages from the server. <br>
Instead of only pulling 20 rows of data, we are able to pull 1000 rows of data (the maximum that the Ticketmaster Public API allows) and returning a dataframe. </p>

In [33]:
def getAllPages(pages=10, per_page=100):
    # url = f'https://app.ticketmaster.com/discovery/v2/events.json?apikey={API_KEY}'
    
    events_params_action_api = {
    'startDateTime': '2025-05-01T18:00:00-05:00',
    'endDateTime': '2027-12-31T17:00:00-05:00',
    'classificationName': 'music',
    # 'dmaId': '345', 
    'city': 'New York',
    'size': '200', 
    'page': '100'
    }
    
    all_records = []

    # url = f'https://app.ticketmaster.com/discovery/v2/events.json?countryCode=US&apikey={API_KEY}'
    url = f'https://app.ticketmaster.com/discovery/v2/events.json?apikey={API_KEY}'

    for page in range(1, pages + 1):         
        response = requests.get(
            url,
            params={**events_params_action_api, 'page': page, 'size': per_page}
        )
        response.raise_for_status()
        records = response.json()
        #(data['_embedded']['events'])
        all_records.extend(records['_embedded']['events'])
        
    return pd.DataFrame(all_records)

### Created a variable `more_events` to call the pagination function `getAllPages()` ###

In [34]:
more_events= getAllPages()

In [35]:
renamed_more_events = more_events.rename(columns= {
    'name':'NAME', 
    'type': 'TYPE', 
    'id': 'ID',
    'classifications': 'GENRE', 
    'accessibility': 'ACCESSIBILITY', 
    'ticketLimit': 'TICKET_LIMIT', 
    '_embedded': 'VENUE_NAME',
    'products': 'PRODUCTS'
}
)

##### <code>more_events.info</code> 
<p> When looking at the updated dataframe of 1000 rows, we see that there are some columns <br>
that contain quite a significant amount of data such as <code>products</code>, <code>ticketLimit</code> and <code>accessibility</code>.

In [36]:
more_events.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             1000 non-null   str
 1   type             1000 non-null   str
 2   id               1000 non-null   str
 3   test             1000 non-null   bool
 4   url              1000 non-null   str
 5   locale           1000 non-null   str
 6   images           1000 non-null   object
 7   sales            1000 non-null   object
 8   dates            1000 non-null   object
 9   classifications  1000 non-null   object
 10  promoter         465 non-null    object
 11  promoters        465 non-null    object
 12  info             648 non-null    str
 13  pleaseNote       821 non-null    str
 14  products         175 non-null    object
 15  seatmap          377 non-null    object
 16  accessibility    186 non-null    object
 17  ticketLimit      346 non-null    object
 18  ageRestrictions  413 non-null    object
 19  ticketing        504 non-null    object
 20  nameOrigin       1000 non-null   str
 21  _links           1000 non-null   object
 22  _embedded        1000 non-null   object
 23  linkMoreInfo     3 non-null      object
 24  outlets          91 non-null     object
 25  doorsTimes       5 non-null      object
 26  priceRanges      474 non-null    object
dtypes: bool(1), object(18), str(8)
memory usage: 846.8+ KB

In [37]:
more_events

,name,type,id,test,url,locale,images,sales,dates,classifications,...,ticketLimit,ageRestrictions,ticketing,nameOrigin,_links,_embedded,linkMoreInfo,outlets,doorsTimes,priceRanges
0,Alabama Shakes,event,G5dYZ_F-Hysua,False,https://www.ticketmaster.com/alabama-shakes-ne...,en-us,[{'url': 'https://s1.ticketm.net/dam/a/359/ad5...,{'public': {'startDateTime': '2026-04-17T14:00...,"{'start': {'localDate': '2026-09-02', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ...",NaN,NaN,NaN,NaN
1,Khalid: It's Always Summer Somewhere Tour,event,G5dYZbzhrO0M1,False,https://www.ticketmaster.com/khalid-its-always...,en-us,"[{'ratio': '4_3', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2025-12-12T15:00...,"{'start': {'localDate': '2026-06-12', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,{'info': 'There is an eight (8) ticket limit f...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZb...,"{'venues': [{'name': 'Radio City Music Hall', ...",NaN,NaN,NaN,NaN
2,YUNGBLUD: IDOLS - THE WORLD TOUR,event,G5dYZbVkK6OTg,False,https://www.ticketmaster.com/yungblud-idols-th...,en-us,"[{'ratio': '4_3', 'url': 'https://s1.ticketm.n...",{'public': {'startDateTime': '2025-10-08T14:00...,"{'start': {'localDate': '2026-06-10', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,{'info': 'There is a four (4) ticket limit for...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZb...,"{'venues': [{'name': 'Radio City Music Hall', ...",NaN,NaN,NaN,NaN
3,Jessie Ware: The Superbloom Tour,event,G5dYZ_kma1OTc,False,https://www.ticketmaster.com/jessie-ware-the-s...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-04-23T13:00...,"{'start': {'localDate': '2026-10-08', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ...",NaN,NaN,NaN,NaN
4,Mon Laferte - Femme Fatale Tour,event,G5dYZ_kppZOWi,False,https://www.ticketmaster.com/mon-laferte-femme...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-03-27T14:00...,"{'start': {'localDate': '2026-08-22', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,{'info': 'There is a six (6) ticket limit for ...,{'legalAgeEnforced': False},"{'safeTix': {'enabled': True}, 'allInclusivePr...",custom,{'self': {'href': '/discovery/v2/events/G5dYZ_...,"{'venues': [{'name': 'Radio City Music Hall', ...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Step Afrika!,event,Z7r9jZ1A7xpG0,False,https://www.ticketmaster.com/event/Z7r9jZ1A7xpG0,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2026-06-19', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,NaN,NaN,{'allInclusivePricing': {'enabled': True}},custom,{'self': {'href': '/discovery/v2/events/Z7r9jZ...,"{'venues': [{'name': 'Joyce Theater - NY', 'ty...",NaN,[{'url': 'https://www.ticketmaster.com/event/Z...,NaN,NaN
996,Step Afrika!,event,Z7r9jZ1A7xpGb,False,https://www.ticketmaster.com/event/Z7r9jZ1A7xpGb,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2026-06-20', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,NaN,NaN,{'allInclusivePricing': {'enabled': True}},custom,{'self': {'href': '/discovery/v2/events/Z7r9jZ...,"{'venues': [{'name': 'Joyce Theater - NY', 'ty...",NaN,[{'url': 'https://www.ticketmaster.com/event/Z...,NaN,NaN
997,Step Afrika!,event,Z7r9jZ1A7xpGx,False,https://www.ticketmaster.com/event/Z7r9jZ1A7xpGx,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2026-06-20', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,NaN,NaN,{'allInclusivePricing': {'enabled': True}},custom,{'self': {'href': '/discovery/v2/events/Z7r9jZ...,"{'venues': [{'name': 'Joyce Theater - NY', 'ty...",NaN,[{'url': 'https://www.ticketmaster.com/event/Z...,NaN,NaN
998,Step Afrika!,event,Z7r9jZ1A7xpG9,False,https://www.ticketmaster.com/event/Z7r9jZ1A7xpG9,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '1900-01-01T06:00...,"{'start': {'localDate': '2026-06-21', 'localTi...","[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,NaN,NaN,{'allInclusivePricing': {'enabled': True}},custom,{'self': {'href': '/discovery/v2/events/Z7r9jZ...,"{'venues': [{'name': 'Joyce Theater - NY', 'ty...",NaN,[{'url': 'https://www.ticketmaster.com/event/Z...,NaN,NaN
999,The World Famous Harlem Gospel Choir,event,rZ7HnEZ1Af0yrd,False,https://www.ticketweb.com/event/the-world-famo...,en-us,"[{'ratio': '16_9', 'url': 'https://s1.ticketm....",{'public': {'startDateTime': '2026-05-26T13:00...,{'access': {'startDateTime': '2026-11-29T17:00...,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",...,NaN,NaN,NaN,custom,{'self': {'href': '/discovery/v2/events/rZ7HnE...,"{'venues': [{'name': 'Blue Note Jazz Club', 't...",NaN,NaN,NaN,"[{'type': 'standard', 'currency': 'USD', 'min'..."

### Created `data_ex` variable to filter for columns that we don't need and renaming columns

In [38]:
data_ex = renamed_more_events.loc[:, ~renamed_more_events.columns.isin(['images','doorsTimes', '_links', 'linkMoreInfo', 'outlets', 'images', 'test','pleaseNote', 'seatmap','nameOrigin', 'promoters', 'url', 'priceRanges', 'locale', 'sales', 'dates','ageRestrictions'])]

In [39]:
# data_ex = more_events.loc[:, ~renamed_more_events.columns.isin(['images','doorsTimes', '_links', 'linkMoreInfo', 'outlets', 'images', 'test','pleaseNote', 'seatmap','nameOrigin', 'promoters', 'url', 'priceRanges', 'locale', 'sales', 'dates','ageRestrictions'])]

In [40]:
data_ex

,NAME,TYPE,ID,GENRE,promoter,info,PRODUCTS,ACCESSIBILITY,TICKET_LIMIT,ticketing,VENUE_NAME
0,Alabama Shakes,event,G5dYZ_F-Hysua,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '466', 'name': 'BOWERY PRESENTS', 'desc...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
1,Khalid: It's Always Summer Somewhere Tour,event,G5dYZbzhrO0M1,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is an eight (8) ticket limit f...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
2,YUNGBLUD: IDOLS - THE WORLD TOUR,event,G5dYZbVkK6OTg,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a four (4) ticket limit for...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
3,Jessie Ware: The Superbloom Tour,event,G5dYZ_kma1OTc,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '466', 'name': 'BOWERY PRESENTS', 'desc...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
4,Mon Laferte - Femme Fatale Tour,event,G5dYZ_kppZOWi,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
...,...,...,...,...,...,...,...,...,...,...,...
995,Step Afrika!,event,Z7r9jZ1A7xpG0,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
996,Step Afrika!,event,Z7r9jZ1A7xpGb,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
997,Step Afrika!,event,Z7r9jZ1A7xpGx,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
998,Step Afrika!,event,Z7r9jZ1A7xpG9,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
999,The World Famous Harlem Gospel Choir,event,rZ7HnEZ1Af0yrd,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,$20 Minimum Per PersonBrunch MenuNO REFUNDS OR...,NaN,NaN,NaN,NaN,"{'venues': [{'name': 'Blue Note Jazz Club', 't..."

In [41]:
data_ex.rename(columns= {
    'name':'NAME', 
    'type': 'TYPE', 
    'id': 'ID',
    'classifications': 'GENRE', 
    'promoter': 'PROMOTER',
    'accessibility': 'ACCESSIBILITY', 
    'ticketLimit': 'TICKET_LIMIT', 
    '_embedded': 'VENUE_NAME',
    'products': 'PRODUCTS',
    'ticketLimit': 'TICKET_LIMIT',
    'info': 'INFO',
    'ticketing': 'TICKETING'


}, inplace=True
)

In [42]:
data_ex

,NAME,TYPE,ID,GENRE,PROMOTER,INFO,PRODUCTS,ACCESSIBILITY,TICKET_LIMIT,TICKETING,VENUE_NAME
0,Alabama Shakes,event,G5dYZ_F-Hysua,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '466', 'name': 'BOWERY PRESENTS', 'desc...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
1,Khalid: It's Always Summer Somewhere Tour,event,G5dYZbzhrO0M1,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is an eight (8) ticket limit f...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
2,YUNGBLUD: IDOLS - THE WORLD TOUR,event,G5dYZbVkK6OTg,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a four (4) ticket limit for...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
3,Jessie Ware: The Superbloom Tour,event,G5dYZ_kma1OTc,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '466', 'name': 'BOWERY PRESENTS', 'desc...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
4,Mon Laferte - Femme Fatale Tour,event,G5dYZ_kppZOWi,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
...,...,...,...,...,...,...,...,...,...,...,...
995,Step Afrika!,event,Z7r9jZ1A7xpG0,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
996,Step Afrika!,event,Z7r9jZ1A7xpGb,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
997,Step Afrika!,event,Z7r9jZ1A7xpGx,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
998,Step Afrika!,event,Z7r9jZ1A7xpG9,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
999,The World Famous Harlem Gospel Choir,event,rZ7HnEZ1Af0yrd,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,$20 Minimum Per PersonBrunch MenuNO REFUNDS OR...,NaN,NaN,NaN,NaN,"{'venues': [{'name': 'Blue Note Jazz Club', 't..."

In [43]:
product_name = data_ex['PRODUCTS']

For the PRODUCTS column, we are missing 827 values out of 1000 rows.

In [44]:
print(data_ex['PRODUCTS'].isna().sum())

825

### This code which worked for the initial 20 rows of data, won't work for 1000 rows of data, since there's some missing products which results in NaN values. ###

In [45]:
# product_name = data_ex['products']
# for item in product_name:
#     for n in item:
#         print(n['name'])

In [46]:
product_name = n['name']

In [47]:
data_ex.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NAME           1000 non-null   str
 1   TYPE           1000 non-null   str
 2   ID             1000 non-null   str
 3   GENRE          1000 non-null   object
 4   PROMOTER       465 non-null    object
 5   INFO           648 non-null    str
 6   PRODUCTS       175 non-null    object
 7   ACCESSIBILITY  186 non-null    object
 8   TICKET_LIMIT   346 non-null    object
 9   TICKETING      504 non-null    object
 10  VENUE_NAME     1000 non-null   object
dtypes: object(7), str(4)
memory usage: 469.0+ KB

In [48]:
# accessibility_mode = data_ex['ACCESSIBILITY'].mode()
# data_ex['ACCESSIBILITY']=data_ex['ACCESSIBILITY'].fillna(accessibility_mode, inplace=True)

In [49]:
data_ex['ACCESSIBILITY']

0      {'ticketLimit': 2}
1      {'ticketLimit': 2}
2      {'ticketLimit': 2}
3      {'ticketLimit': 2}
4      {'ticketLimit': 2}
              ...
995                   NaN
996                   NaN
997                   NaN
998                   NaN
999                   NaN
Name: ACCESSIBILITY, Length: 1000, dtype: object

In [50]:
data_ex

,NAME,TYPE,ID,GENRE,PROMOTER,INFO,PRODUCTS,ACCESSIBILITY,TICKET_LIMIT,TICKETING,VENUE_NAME
0,Alabama Shakes,event,G5dYZ_F-Hysua,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '466', 'name': 'BOWERY PRESENTS', 'desc...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
1,Khalid: It's Always Summer Somewhere Tour,event,G5dYZbzhrO0M1,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is an eight (8) ticket limit f...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
2,YUNGBLUD: IDOLS - THE WORLD TOUR,event,G5dYZbVkK6OTg,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a four (4) ticket limit for...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
3,Jessie Ware: The Superbloom Tour,event,G5dYZ_kma1OTc,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '466', 'name': 'BOWERY PRESENTS', 'desc...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
4,Mon Laferte - Femme Fatale Tour,event,G5dYZ_kppZOWi,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ..."
...,...,...,...,...,...,...,...,...,...,...,...
995,Step Afrika!,event,Z7r9jZ1A7xpG0,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
996,Step Afrika!,event,Z7r9jZ1A7xpGb,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
997,Step Afrika!,event,Z7r9jZ1A7xpGx,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
998,Step Afrika!,event,Z7r9jZ1A7xpG9,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,NaN,NaN,NaN,NaN,{'allInclusivePricing': {'enabled': True}},"{'venues': [{'name': 'Joyce Theater - NY', 'ty..."
999,The World Famous Harlem Gospel Choir,event,rZ7HnEZ1Af0yrd,"[{'primary': True, 'segment': {'id': 'KZFzniwn...",NaN,$20 Minimum Per PersonBrunch MenuNO REFUNDS OR...,NaN,NaN,NaN,NaN,"{'venues': [{'name': 'Blue Note Jazz Club', 't..."

<p> We don't want to arbitrarily drop NAN values for the missing values in 
<code>Products</code>, <code>Accessibility</code>, <br><code>Genre</code> and 
<code>Venues</code> since this would introduce a bias due to the large 
number of missing values. 

<!-- #### Dropping NAN values for Products, Accessibility, Genre column, Venues Name column and making a copy while retaining original column values. ####  -->

In [51]:
data_ex.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NAME           1000 non-null   str
 1   TYPE           1000 non-null   str
 2   ID             1000 non-null   str
 3   GENRE          1000 non-null   object
 4   PROMOTER       465 non-null    object
 5   INFO           648 non-null    str
 6   PRODUCTS       175 non-null    object
 7   ACCESSIBILITY  186 non-null    object
 8   TICKET_LIMIT   346 non-null    object
 9   TICKETING      504 non-null    object
 10  VENUE_NAME     1000 non-null   object
dtypes: object(7), str(4)
memory usage: 469.0+ KB

##### For the <code>data_ex['PRODUCTS']</code>, we only have values for 173 rows out of 1000 (missing 827 rows of data). We are not able to take the mean since this column is categorical and fill in the NaN rows, so I'm not sure how else to resolve this.

In [52]:
data_ex['PRODUCTS']

0      [{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...
1      [{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...
2      [{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...
3      [{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...
4      [{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...
                             ...
995                                                  NaN
996                                                  NaN
997                                                  NaN
998                                                  NaN
999                                                  NaN
Name: PRODUCTS, Length: 1000, dtype: object

In [53]:
data_clean = data_ex.dropna(subset = ['PRODUCTS', 'ACCESSIBILITY']).copy()

In [54]:
data_clean.rename(columns= {
    'name':'NAME', 
    'type': 'TYPE', 
    'id': 'ID',
    'classifications': 'GENRE', 
    'promoter': 'PROMOTER',
    'ticketLimit': 'TICKET_LIMIT', 
    '_embedded': 'VENUE_NAME',
    'ticketLimit': 'TICKET_LIMIT',
    'info': 'INFO',
    'products': 'PRODUCTS',
    'accessibility': 'ACCESSIBILITY',
    'ticketing': 'TICKETING' ,
    'Accessibility_Filtered': 'ACCESSIBILITY_Filtered'
    


}, inplace=True
)

#### List comprehension to create new dataframe after dropped NaN values to create new column for 'Products_Filtered' ####

In [55]:
# data_clean['PRODUCTS_Filtered'] = [
#     [n['name'] for n in item] for item in data_clean['PRODUCTS']
# ] #list of products name

data_clean['PRODUCTS_Filtered'] = [
    ', '.join([n['name'] for n in item]) for item in data_clean['PRODUCTS']
]
#converted list of products using comma separator

In [56]:
data_clean['VENUE_NAME_Filtered'] = [
    name['venues'][0]['name']
    for name in data_clean['VENUE_NAME']
    
    
]
data_clean['Accessibility_Filtered'] = [
    f"Ticket Limit: {item.get('ticketLimit', 'N/A')}" for item in data_clean['ACCESSIBILITY']
]


data_clean['Genre_Filtered'] = [item['genre']['name']
                                for x in data_clean['GENRE']
                                for item in x
    ]

#### Final Dataframe version ####

In [57]:
data_clean

,NAME,TYPE,ID,GENRE,PROMOTER,INFO,PRODUCTS,ACCESSIBILITY,TICKET_LIMIT,TICKETING,VENUE_NAME,PRODUCTS_Filtered,VENUE_NAME_Filtered,Accessibility_Filtered,Genre_Filtered
0,Alabama Shakes,event,G5dYZ_F-Hysua,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '466', 'name': 'BOWERY PRESENTS', 'desc...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ...",SPOTHERO RADIO CITY MUSIC HALL,Radio City Music Hall,Ticket Limit: 2,Rock
1,Khalid: It's Always Summer Somewhere Tour,event,G5dYZbzhrO0M1,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is an eight (8) ticket limit f...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ...",SPOTHERO RADIO CITY MUSIC HALL,Radio City Music Hall,Ticket Limit: 2,R&B
2,YUNGBLUD: IDOLS - THE WORLD TOUR,event,G5dYZbVkK6OTg,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a four (4) ticket limit for...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ...",SPOTHERO RADIO CITY MUSIC HALL,Radio City Music Hall,Ticket Limit: 2,Rock
3,Jessie Ware: The Superbloom Tour,event,G5dYZ_kma1OTc,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '466', 'name': 'BOWERY PRESENTS', 'desc...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ...",SPOTHERO RADIO CITY MUSIC HALL,Radio City Music Hall,Ticket Limit: 2,Rock
4,Mon Laferte - Femme Fatale Tour,event,G5dYZ_kppZOWi,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '653', 'name': 'LIVE NATION MUSIC', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO RADIO CITY MUSIC HALL', 'i...",{'ticketLimit': 2},{'info': 'There is a six (6) ticket limit for ...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Radio City Music Hall', ...",SPOTHERO RADIO CITY MUSIC HALL,Radio City Music Hall,Ticket Limit: 2,Pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,Myriam Hernandez - Tauro Usa Tour 2026,event,k7vGFbzEbiDTb,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '494', 'name': 'PROMOTED BY VENUE', 'de...",NaN,"[{'name': 'PARKWHIZ UNITED PALACE', 'id': 'k7v...",{'ticketLimit': 4},NaN,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'United Palace', 'type': ...",PARKWHIZ UNITED PALACE,United Palace,Ticket Limit: 4,Latin
669,Tribeca Festival Presents Sara Bareilles: Good...,event,G5diZ_FcMIo9S,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '494', 'name': 'PROMOTED BY VENUE', 'de...",PLEASE NOTE: Pricing is all-in and includes fe...,"[{'name': 'SPOTHERO BEACON THEATRE', 'id': 'G5...",{'ticketLimit': 4},{'info': 'There is an eight (8) ticket limit p...,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Beacon Theatre', 'type':...",SPOTHERO BEACON THEATRE,Beacon Theatre,Ticket Limit: 4,Miscellaneous Theatre
671,Tony Vega,event,k7vGFbVrPcvA_,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '494', 'name': 'PROMOTED BY VENUE', 'de...",NaN,"[{'name': 'PARKWHIZ UNITED PALACE', 'id': 'k7v...",{'ticketLimit': 4},NaN,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'United Palace', 'type': ...",PARKWHIZ UNITED PALACE,United Palace,Ticket Limit: 4,Latin
672,La Dinastia Rosario,event,k7vGF_ddMZ_Ov,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '494', 'name': 'PROMOTED BY VENUE', 'de...",Hermanos Rosario & Toño Rosario,"[{'name': 'PARKWHIZ UNITED PALACE', 'id': 'k7v...",{'ticketLimit': 4},NaN,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'United Palace', 'type': ...",PARKWHIZ UNITED PALACE,United Palace,Ticket Limit: 4,Latin
841,Luna,event,k7vGF_52RV_QK,"[{'primary': True, 'segment': {'id': 'KZFzniwn...","{'id': '494', 'name': 'PROMOTED BY VENUE', 'de...",NaN,"[{'name': 'PARKWHIZ SONY HALL', 'id': 'k7vGF_5...",{},NaN,"{'safeTix': {'enabled': True}, 'allInclusivePr...","{'venues': [{'name': 'Sony Hall', 'type': 'ven...",PARKWHIZ SONY HALL,Sony Hall,Ticket Limit: N/A,Rock

##### Reordering columns for **'Accessibility_Filtered', 'Products_Filtered', 'Genre_Filtered', 'VENUE_NAME_Filtered** to position them next to the original data. #####

In [58]:
move_col1=data_clean.pop('Accessibility_Filtered')
data_clean.insert(9, column='Accessibility_Filtered', value=move_col1)

move_col2 = data_clean.pop('Genre_Filtered')
data_clean.insert(4, column='Genre_Filtered', value=move_col2)

move_col3 = data_clean.pop('PROMOTER')
data_clean.insert(10, column='PROMOTER',value=move_col3 )

move_col4 = data_clean.pop('VENUE_NAME_Filtered')
data_clean.insert(6, column='VENUE_NAME_Filtered', value=move_col4)

move_col5 = data_clean.pop('INFO')
data_clean.insert(11, column='INFO', value=move_col5)

move_col6 = data_clean.pop('VENUE_NAME')
data_clean.insert(5, column='VENUE_NAME', value=move_col6)

move_col7 = data_clean.pop('PRODUCTS')
data_clean.insert(7, column='PRODUCTS', value=move_col7)

move_col8 = data_clean.pop('PRODUCTS_Filtered') #Not sure why 'Products_Filtered' appears two times. 
data_clean.insert(8, column='PRODUCTS_Filtered', value=move_col8)

#### Final Dataframe ####

In [64]:
data_clean.to_csv('data/processed/TicketMaster.csv')

In [60]:
data_clean.info()

<class 'pandas.DataFrame'>
Index: 162 entries, 0 to 841
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NAME                    162 non-null    str
 1   TYPE                    162 non-null    str
 2   ID                      162 non-null    str
 3   GENRE                   162 non-null    object
 4   Genre_Filtered          162 non-null    str
 5   VENUE_NAME              162 non-null    object
 6   VENUE_NAME_Filtered     162 non-null    str
 7   PRODUCTS                162 non-null    object
 8   PRODUCTS_Filtered       162 non-null    str
 9   ACCESSIBILITY           162 non-null    object
 10  TICKET_LIMIT            143 non-null    object
 11  Accessibility_Filtered  162 non-null    str
 12  PROMOTER                162 non-null    object
 13  INFO                    141 non-null    str
 14  TICKETING               162 non-null    object
dtypes: object(7), str(8)
memory usage: 99.3+ KB

##### *Used AI-generated code for filtering* ####

In [61]:
data_clean['ACCESSIBILITY'].apply(lambda x: list(x.keys())).value_counts()

ACCESSIBILITY
[ticketLimit]    159
[]                 3
Name: count, dtype: int64

### Code for looping inside Accessibility column and removing NaN values using list comprehension in data_clean dataframe ###

In [62]:
# data_clean['Accessibility_Filtered'] = [
#     f'Ticket Limit: {value}'
#     for item in accessibility
#     for location, value in item.items()]

print(data_ex['ACCESSIBILITY'].isna().sum())

814

### Using list comprehension in data_clean dataframe ###

In [63]:
for x in genre: #x is the dictionary
    for item in x:
        print(item['genre']['name']) 
        #loop through Genre list to pull Genre name.

Rock
Rock
R&B
Rock
Pop
Rock
Rock
Country
Latin
R&B
Latin
Rock
Rock
Rock
Country
Country
Rock
Rock
Rock
Rock